language: objective-c
osx_image: xcode9.2

git:
    depth: 5 # Limit unneeded commit depth
    submodules: false

before_install:
    - set -o pipefail # Prevent xcpretty from eating xcodebuild's exit code
    - git submodule update --init --recursive

install:
    - gem install xcov --no-ri --no-rdoc        # For generating coverage reports
    - gem install xcpretty --no-ri --no-rdoc    # For cleaning xcodebuild output
    - gem install cocoapods --no-ri --no-rdoc
    - pod update
    - pod install

script:
    - ./test.sh # Run test script

after_success:
    - xcov -w SplitSound.xcworkspace -s SplitSound -q Debug --coveralls_service_name travis-ci --coveralls_service_job ${CI_BUILD_NUMBER} -o xcov-output # Generate coverage reports and upload to coveralls
