language: objective-c
osx_image: xcode9.2

git:
    depth: 5 # Limit unneeded commit depth
    submodules: false

before_install:
    - set -o pipefail # Prevent xcpretty from eating xcodebuild's exit code
    - git submodule update --init --recursive

install:
    - gem install cocoapods
    - pod update
    - pod install

before_script:
    - gem install xcpretty # Clean xcodebuild output

script:
    - ./test.sh # Call test script
