language: objective-c
osx_image: xcode9.2

git:
    depth: 5 # Limit unneeded commit depth
    submodules: false

before_install:
    - git submodule update --init --recursive

before_script:
    - gem install xcpretty

script:
    - xcodebuild test -project SplitSound.xcodeproj -scheme SplitSound -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8,OS=latest' | xcpretty --color; exit ${PIPESTATUS[0]}
