language: objective-c
osx_image: xcode9.2

git:
    depth: 5 # Limit unneeded commit depth
    submodules: false

before_install:
    - set -o pipefail # Prevent xcpretty from eating xcodebuild's exit code
    - git submodule update --init --recursive

install:
    - gem install xcov --no-ri --no-rdoc        # For generating coverage reports
    - gem install xcpretty --no-ri --no-rdoc    # For cleaning xcodebuild output
    - gem install cocoapods --no-ri --no-rdoc
    - pod update
    - pod install

script:
    - ./test.sh # Run test script

after_success:
    - xcov -w SplitSound.xcworkspace -s SplitSound -q Debug --coveralls_repo_token $COVERALLS_REPO_TOKEN -o xcov-output # Generate coverage reports and upload to coveralls (relies on secure travis env variable)
    - curl https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh > send.sh
    - chmod +x send.sh
    - ./send.sh success $WEBHOOK_URL # Webhook to Discord


after_failure:
    - curl https://raw.githubusercontent.com/k3rn31p4nic/travis-ci-discord-webhook/master/send.sh > send.sh
    - chmod +x send.sh
    - ./send.sh failure $WEBHOOK_URL # Webhook to Discord
